org.gradle.java.home=E\:/DevTools/Android\ Studio/jbr
org.gradle.jvmargs=-Xmx4g -XX:+UseG1GC -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=false

# Optimization flags for smaller APK size
android.enableR8.fullMode=true
android.enableResourceOptimizations=true
kotlin.incremental=false
kotlin.incremental.useClasspathSnapshot=false
