org.gradle.java.home=E\:/DevTools/Android\ Studio/jbr
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.vfs.watch=false
org.gradle.daemon=true

# Optimization flags for smaller APK size
android.enableR8.fullMode=true
android.enableResourceOptimizations=true
kotlin.incremental=false
android.suppressUnsupportedCompileSdk=35,36
systemProp.org.gradle.internal.http.connectionTimeout=120000
systemProp.org.gradle.internal.http.socketTimeout=120000
